### PR TITLE
Bumping angular devkit to support angular 14

### PR DESCRIPTION
**Pull request by Maciej-Bartoszek**

### CODE REVIEW

**Comment by migalons** [comment]
Hey @mbartoszek-lawlogix.

Thanks for the update. I will merge it and publish a new version. But it will take me some working days, since I had an issue with my npmjs account.

I will let you know when this is done. 

Regards.

**Comment by Maciej-Bartoszek** [comment]
Hey @migalons
I've noticed that builder process was not ending properly. Found this issue: https://github.com/angular/angular-cli/issues/24120 so I've added process.exit(exitCode) and after further testing now it is working well.

**Comment by migalons** [comment]
Hi @mbartoszek-lawlogix. Thanks for the update.

Please squash your commits, and I will test it and publish a new version during this week.

Regards.

**Comment by Maciej-Bartoszek** [comment]
Hey @migalons do we have any updates on this?

**Comment by migalons** [comment]
Done and published into npmjs

**Pull request merged**
